### ISSUE TITLE
Typo in readme equation?

### ISSUE THREAD

**Issue by mdavis-xyz** [damiancclarke/eventdd#1]
In the first equation in the README, should there be a coefficient inside the second sum, before `Lag`?

I was expecting leads and lags to be symmetric.

I can add this with a PR, but I don't know which greek letter to use. (Should we re-use beta? Then the indices will clash between leads and lags.)

**Comment by damiancclarke** [comment]
Thanks very much @mdavis-xyz!  This is right -- the coefficient is missing.  If you want to put in a pull request, I'm happy make the pull!  Perhaps gamma is ideal, as this lines up with the notation in the SJ paper?  Thanks so much!
