### ISSUE TITLE
option over not allowed r(198);

### ISSUE THREAD

**Issue by TXU0429** [damiancclarke/eventdd#3]
Hi, 

I have been trying the eventdd package and it has been very useful. Thank you for the package! 

When I was trying the [Bhalotra et al. (2023)] Reserved Seat Quota Adoption and Maternal Mortality example code for a graph using the code from README.md
eventdd lnmmrt i.year, timevar(timeToTreat) method(hdfe, absorb(country) cluster(country)) lags(10) leads(10) accum over(GDPp25) jitter(0.2) graph_op(ytitle("ln(Maternal Mortality)") legend(pos(6) order(2 "Point Estimate (GDP {&ge} 25 p)" 5 "Point Estimate (GDP < 25 p)" 1 "95% CI") rows(1)) ylabel(, format("%04.2f"))) coef_op(g1(ms(Sh)) g2(ms(Oh))) ci(rarea, g1(color(gs12%30)) g2(color(gs12%50))) 

I got the following error:
option over not allowed
r(198);

Any idea what is wrong here? 

Thank you in advance.

**Comment by damiancclarke** [comment]
Hello, I suspect that this might be an error message that owes to a previous version of the package being installed.  Do you know if you have the most recent version installed?   If you type `which eventdd` you should see Version 4.0.0.  If you don't, you can update with `ssc install eventdd, replace`, and then the above code should run.

**Comment by TXU0429** [comment]
> Hello, I suspect that this might be an error message that owes to a previous version of the package being installed. Do you know if you have the most recent version installed? If you type `which eventdd` you should see Version 4.0.0. If you don't, you can update with `ssc install eventdd, replace`, and then the above code should run.

Thank you for your reply! I solved the problem by reinstalling the package.

**Comment by damiancclarke** [comment]
Great, thanks for updating this!  Will mark as closed.
